spring:
  datasource:
    name: coding_assignment_becare_debug_dev
    url: jdbc:h2:file:./.h2/coding_assignment_becare_debug_dev;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
